name = "tracker-web-backend"
type = "javascript"
workers_dev = true
compatibility_date = "2022-01-20"

[[kv_namespaces]]
binding = "TRACKER_KV"
id = "e78738a9d9a843b08b385d292bcfc811"
preview_id = "f282db37656b409dac442d96c954151c"

[vars]
WORKERS_RS_VERSION = "0.0.9"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
