name = "tracker-web-backend"
type = "javascript"
workers_dev = true
compatibility_date = "2022-01-20"

kv_namespaces = [
  { binding = "TRACKER_KV", id = "", preview_id = "5e9052702796417392287143300924f8" }
]

[vars]
WORKERS_RS_VERSION = "0.0.9"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
