[package]
name = "tracker_core"
version = "0.8.1"
edition = "2021"

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
log = "^0.4"
chrono = { version = "^0.4", features = ["serde"] }
thiserror = "^1.0"

[dev-dependencies]
rstest = "0.13"
serde_json = "^1.0"